import { NgModule } from '@angular/core';
import {
  MatButtonModule,
  MatFormFieldModule,
  MatInputModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatCheckboxModule,
  MatRadioModule,
  MatCardModule,
  MatDividerModule,
  MatIconModule,
  MatSidenavModule,
  MatToolbarModule,
  MatBadgeModule,
  MatListModule,
  MatExpansionModule,
  MatRippleModule,
  MatButtonToggleModule,
  MatTabsModule,
  MatSliderModule,
  MatTooltipModule,
  MatSelectModule,
  MatDialogModule,
  MatTreeModule,
  MatProgressSpinnerModule,
  MatTableModule,
  MatSortModule,
  MatPaginatorModule,
  MatSnackBarModule,
  MatAutocompleteModule,
  MatProgressBarModule

} from '@angular/material';

@NgModule({
  imports: [
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatCheckboxModule,
    MatRadioModule,
    MatCardModule,
    MatDividerModule,
    MatIconModule,
    MatSidenavModule,
    MatToolbarModule,
    MatBadgeModule,
    MatListModule,
    MatExpansionModule,
    MatRippleModule,
    MatButtonToggleModule,
    MatTabsModule,
    MatSliderModule,
    MatTooltipModule,
    MatSelectModule,
    MatDialogModule,
    MatTreeModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
    MatSnackBarModule,
    MatAutocompleteModule,
    MatProgressBarModule

  ],
  exports: [
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatCheckboxModule,
    MatRadioModule,
    MatCardModule,
    MatDividerModule,
    MatIconModule,
    MatSidenavModule,
    MatToolbarModule,
    MatBadgeModule,
    MatListModule,
    MatExpansionModule,
    MatRippleModule,
    MatButtonToggleModule,
    MatTabsModule,
    MatSliderModule,
    MatTooltipModule,
    MatSelectModule,
    MatDialogModule,
    MatTreeModule,
    MatProgressSpinnerModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
    MatSnackBarModule,
    MatAutocompleteModule,
    MatProgressBarModule

  ]
})
export class MaterialModule {}
